# Generated by Django 4.1.3 on 2022-11-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answer_rating_question_rating_alter_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='like_flag',
            field=models.BooleanField(default=True, verbose_name='like_dislike'),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='like_flag',
            field=models.BooleanField(default=True, verbose_name='like_dislike'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.profile'),
        ),
    ]
